import type { LucideIcon } from "lucide-react";
import {
  ShoppingCart,
  ShoppingBasket,
  UtensilsCrossed,
  Coffee,
  Beer,
  Wine,
  Pizza,
  IceCreamCone,
  Croissant,
  Home,
  KeyRound,
  Hammer,
  Wrench,
  Paintbrush,
  Plug,
  Droplet,
  Flame,
  Sofa,
  BedDouble,
  Bath,
  Flower2,
  Leaf,
  TreePine,
  Car,
  Fuel,
  Bus,
  TrainFront,
  Plane,
  Bike,
  ParkingCircle,
  Sailboat,
  Truck,
  TicketCheck,
  Shirt,
  Footprints,
  Scissors,
  Gem,
  Glasses,
  Watch,
  Gamepad2,
  Music,
  Clapperboard,
  BookOpen,
  Ticket,
  Dices,
  Palette,
  Camera,
  Tv,
  Headphones,
  PartyPopper,
  Mic2,
  HeartPulse,
  Pill,
  Stethoscope,
  BandageIcon,
  Dumbbell,
  Sparkles,
  Brain,
  CalendarClock,
  Smartphone,
  Wifi,
  Laptop,
  Tv2,
  Newspaper,
  Cloud,
  Zap,
  Sun,
  BatteryCharging,
  Luggage,
  Tent,
  Mountain,
  Palmtree,
  Globe,
  MapPin,
  Compass,
  Gift,
  PiggyBank,
  Wallet,
  CreditCard,
  Coins,
  Banknote,
  TrendingUp,
  Landmark,
  HandCoins,
  Receipt,
  GraduationCap,
  Pencil,
  Backpack,
  Baby,
  Puzzle,
  Dog,
  Cat,
  PawPrint,
  Briefcase,
  FileText,
  Building2,
  Mail,
  Printer,
  Percent,
  Waves,
  Trophy,
  Target,
  Shield,
  Umbrella,
  Tag,
  Star,
  CircleEllipsis,
} from "lucide-react";

const TRACES: Record<string, LucideIcon> = {
  courses: ShoppingCart,
  epicerie: ShoppingBasket,
  restaurant: UtensilsCrossed,
  cafe: Coffee,
  bar: Beer,
  vin: Wine,
  fast_food: Pizza,
  dessert: IceCreamCone,
  boulangerie: Croissant,

  maison: Home,
  loyer: KeyRound,
  bricolage: Hammer,
  outils: Wrench,
  peinture: Paintbrush,
  electricite: Plug,
  eau: Droplet,
  gaz: Flame,
  mobilier: Sofa,
  literie: BedDouble,
  salle_de_bain: Bath,
  jardin: Flower2,
  plantes: Leaf,
  arbres: TreePine,

  transport: Car,
  essence: Fuel,
  bus: Bus,
  train: TrainFront,
  avion: Plane,
  velo: Bike,
  parking: ParkingCircle,
  bateau: Sailboat,
  camion: Truck,
  peage: TicketCheck,

  vetements: Shirt,
  chaussures: Footprints,
  coiffeur: Scissors,
  bijoux: Gem,
  lunettes: Glasses,
  montre: Watch,

  loisirs: Gamepad2,
  musique: Music,
  cinema: Clapperboard,
  lecture: BookOpen,
  spectacle: Ticket,
  jeux: Dices,
  art: Palette,
  photo: Camera,
  tele: Tv,
  podcast: Headphones,
  fete: PartyPopper,
  concert: Mic2,

  sante: HeartPulse,
  pharmacie: Pill,
  medecin: Stethoscope,
  soins: BandageIcon,
  sport: Dumbbell,
  bienetre: Sparkles,
  mental: Brain,

  abonnement: CalendarClock,
  telephone: Smartphone,
  internet: Wifi,
  informatique: Laptop,
  streaming: Tv2,
  presse: Newspaper,
  cloud: Cloud,

  energie: Zap,
  solaire: Sun,
  batterie: BatteryCharging,

  voyage: Luggage,
  camping: Tent,
  montagne: Mountain,
  plage: Palmtree,
  monde: Globe,
  itineraire: MapPin,
  boussole: Compass,

  cadeau: Gift,

  epargne: PiggyBank,
  portefeuille: Wallet,
  carte_bancaire: CreditCard,
  pieces: Coins,
  billets: Banknote,
  investissement: TrendingUp,
  banque: Landmark,
  don: HandCoins,
  facture: Receipt,

  education: GraduationCap,
  fournitures: Pencil,
  cartable: Backpack,
  bebe: Baby,
  jouets: Puzzle,

  animaux: Dog,
  chat: Cat,
  veterinaire: PawPrint,

  travail: Briefcase,
  documents: FileText,
  entreprise: Building2,
  courrier: Mail,
  impression: Printer,
  impots: Percent,

  natation: Waves,
  trophee: Trophy,
  cible: Target,

  assurance: Shield,
  parapluie: Umbrella,
  etiquette: Tag,
  favori: Star,
  autre: CircleEllipsis,
};

export function IconeCategorie({ icone, className }: { icone?: string | null; className?: string }) {
  const Trace = (icone && TRACES[icone]) || TRACES.autre;
  return <Trace className={className ?? "h-5 w-5"} strokeWidth={1.7} />;
}
